SELECT u.USERS_NAME , q.QST_ID, q.QST_TITLE, 
   q.QST_CONTENT, q.QST_REGDATE, r.RPY_ID , 
   r.RPY_REF , r.RPY_CONTENT , r.RPY_STATUS 
   FROM QUESTBOARD q ,USERSINFO u, REPLYBOARD r 
   WHERE q.QST_ID = u.USERS_ID 
   AND q.QST_SEQ = r.RPY_REF
   AND (q.QST_STATUS = 'Y' OR r.RPY_STATUS = 'Y')
   AND q.QST_SEQ = 'Q2'
    ORDER BY r.RPY_SEQ DESC;

   
UPDATE USERSINFO SET USERS_STATUS='S' WHERE USERS_ID IN (gana@naver.com, nada@naver.com);

UPDATE USERSINFO SET USERS_STATUS='S' WHERE USERS_ID IN ('gana@naver.com', 'nada@naver.com');

SELECT *
	FROM USERSINFO u ;