SELECT u.USERS_NAME , q.QST_ID, q.QST_TITLE, 
   q.QST_CONTENT, q.QST_REGDATE, r.RPY_ID , 
   r.RPY_REF , r.RPY_CONTENT , r.RPY_STATUS 
   FROM QUESTBOARD q ,USERSINFO u, REPLYBOARD r 
   WHERE q.QST_ID = u.USERS_ID 
   AND q.QST_SEQ = r.RPY_REF
   AND (q.QST_STATUS = 'Y' OR r.RPY_STATUS = 'Y')
   AND q.QST_SEQ = 'Q2'
    ORDER BY r.RPY_SEQ DESC;

   
UPDATE USERSINFO SET USERS_STATUS='S' WHERE USERS_ID IN (gana@naver.com, nada@naver.com);

UPDATE USERSINFO SET USERS_STATUS='S' WHERE USERS_ID IN ('gana@naver.com', 'nada@naver.com');

SELECT *
	FROM USERSINFO u ;
	
SELECT COUNT(*) 
	FROM USERSINFO u
	WHERE USERS_ID = 'elsa@disney.com';
	

--추가정보 입력

UPDATE USERSINFO
SET USERS_ADDR='서울특별시 중구 마장로5길 10', USERS_SUBTEL='01122223333'
WHERE USERS_ID='gggg'

SELECT *
	FROM USERSINFO u 
	WHERE USERS_ID = 'gggg';

SELECT NVL(MAX(PET_SEQ),0)+1 FROM PETSINFO;

INSERT INTO PETSINFO
(PET_SEQ,
	PET_OWNER, PET_NAME, PET_BDAY, PET_SPECIES, PET_GENDER, PET_NEUT, PET_REPORT)
VALUES((SELECT NVL(MAX(PET_SEQ),0)+1 FROM PETSINFO),
	'gggg', '쪼푸', '20220731', 'D', 'M', 'N', '귀여운 우리집 쪼푸');

SELECT *
	FROM PETSINFO;

SELECT USERS_ID 
	FROM USERSINFO u
	WHERE USERS_PW = 'elsa1234';
	

-- 아이디 찾기
SELECT NVL(USERS_ID, 0) AS USERS_ID 
	FROM USERSINFO u
	WHERE USERS_NAME = '김당망' AND USERS_TEL = '0101234123';