SELECT r.RPY_SEQ, r.RPY_CONTENT, r.RPY_REGDATE
	FROM REPLYBOARD r JOIN QUESTBOARD q
	WHERE r.RPY_REF = q.QST_SEQ
	ON q.QST_SEQ = 'Q1';
	
SELECT r.RPY_SEQ, h.HOSP_NAME, r.RPY_CONTENT, r.RPY_REGDATE
	FROM REPLYBOARD r
	JOIN QUESTBOARD q ON r.RPY_REF = q.QST_SEQ
	JOIN HOSPITAL h ON r.RPY_ID = h.HOSP_ID
	WHERE q.QST_SEQ = 'Q3';