SELECT 'M'|| MAX(TO_NUMBER(SUBSTR(MEDI_NUM,2)))
	FROM MEDICHART m;

SELECT NVL(MAX(F_SEQ),0)+1 FROM FILEBOARD;
	
INSERT INTO PROJECT.FILEBOARD
(F_SEQ, F_REF, F_ORIGINNAME, F_STOREDNAME, F_SIZE, F_DELFLAG)
VALUES((SELECT NVL(MAX(F_SEQ),0)+1 FROM FILEBOARD), '', '', '', 0, 'N' );

SELECT m.MEDI_NUM, m.MEDI_ID , m.MPET_SEQ , 
				p.PET_NAME, m.MEDI_L , m2.MEDI_NAME , 
				m.MEDI_S , m3.MEDI_NAME, DBMS_LOB.SUBSTR(m.MEDI_CONTENT,DBMS_LOB.GETLENGTH(m.MEDI_CONTENT)) , m.MEDI_VISIT  
			FROM MEDICHART m 
			JOIN MEDICODE m2 ON m.MEDI_L = m2.MEDI_CODE 
			LEFT JOIN MEDICODE m3 ON m.MEDI_S = m3.MEDI_CODE 
			JOIN PETSINFO p ON m.MPET_SEQ = p.PET_SEQ 
			WHERE MEDI_ID =#{medi_id}
			AND MEDI_DELFLAG ='N'
			AND MEDI_NUM =#{medi_num}
			ORDER BY MEDI_VISIT DESC
			
  SELECT p.PET_SEQ ,p.PET_OWNER, p.PET_NAME, TO_CHAR(p.PET_BDAY,'YYYY-MM-DD'),
				p.PET_SPECIES ,p.PET_GENDER, p.PET_NEUT ,p.PET_REPORT ,
				m.MEDI_NUM ,TO_CHAR(m.MEDI_VISIT,'YYYY-MM-DD')  , 
				m.MEDI_L, m2.MEDI_NAME AS MEDI_LNAME , m.MEDI_S, m3.MEDI_NAME AS MEDI_SNAME , 
				m.MEDI_TITLE , m.MEDI_CONTENT ,m.MEDI_DELFLAG
			FROM PETSINFO p 
			JOIN MEDICHART m ON p.PET_SEQ = m.MPET_SEQ 
			LEFT JOIN MEDICODE m2 ON m.MEDI_L = m2.MEDI_CODE 
			LEFT JOIN MEDICODE m3 ON m.MEDI_S = m3.MEDI_CODE 
			WHERE m.MEDI_NUM ='M9'
			AND m.MEDI_DELFLAG ='N'
			ORDER BY m.MEDI_VISIT DESC